annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: '>=1.22'
apiVersion: v2
appVersion: 0.12.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami/
  version: 1.16.1
description: Set of components that automatically adjust the amount of CPU and memory
  requested by pods running in the Kubernetes Cluster
home: https://github.com/kubernetes/autoscaler
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
maintainers:
- email: sebastien.prudhomme@gmail.com
  name: sebastien-prudhomme
name: vertical-pod-autoscaler
sources:
- https://github.com/kubernetes/autoscaler
- https://github.com/cowboysysop/charts/tree/master/charts/vertical-pod-autoscaler
version: 6.0.2
