apiVersion: apps/v1
kind: Deployment
metadata:
  name: halloween-deployment
  labels:
    app: halloween
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halloween
  template:
    metadata:
      labels:
        app: halloween
    spec:
      containers:
        - name: halloween
          image: leonardtia/tia:halloween
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: halloween-nodeport-service
  labels:
    app: halloween
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /index.html
spec:
  type: NodePort
  selector:
    app: halloween
  ports:
    - port: 80
      targetPort: 80

   