controller:
  replicaCount: 2
  nodeSelector:
    "kubernetes.io/os": "linux"
  service:
    externalTrafficPolicy: Local
  defaultBackend:
    nodeSelector:
      "kubernetes.io/os": "linux"
namespace: ingress-nginx